import type { Locale } from '@/i18n/config';

/** Textos de los bloques del embudo (brief biblioteca §4). Sin presión: valor primero. */
export const FUNNEL = {
  es: {
    toolEyebrow: 'Herramienta gratis',
    toolCta: 'Usar la herramienta',
    productEyebrow: 'Si quieres ir más allá',
    seeProduct: 'Ver demo gratis',
    seeService: 'Ver cómo funciona',
    buy: 'Comprar',
    launch: 'Precio de lanzamiento',
    full: 'Plazas completas esta semana. Apúntate y te aviso en cuanto haya hueco.',
    consentRequired: 'Marca la casilla para continuar con la compra.',
    waitlistTitle: 'Próximamente',
    waitlistBody: 'Estoy preparando este programa. Apúntate y te aviso el primero cuando esté listo.',
    waitlistServiceBody: 'Muy pronto podrás reservarla aquí. Apúntate y te aviso en cuanto abra las plazas.',
    waitlistGeneralTitle: 'Los programas están en camino',
    waitlistGeneralBody: 'Guías y programas para entrenar por tu cuenta con un método claro. Apúntate y te aviso en cuanto salga el primero.',
    waitlistSubmit: 'Avisarme',
    waitlistSuccess: 'Apuntado. Te escribo en cuanto esté disponible.',
    coachingEyebrow: 'Coaching 1:1',
    coachingTitle: '¿Prefieres que lo hagamos juntos?',
    coachingBody: 'Plan hecho para ti, revisión semanal y contacto directo conmigo. Empezamos con una videollamada para ver si encajamos.',
    coachingCta: 'Ver el coaching',
    applyCta: 'Solicitar plaza',
    authorLabel: 'Escrito por',
    authorMore: 'Sobre mí',
    adLabel: 'Recomendado',
  },
  en: {
    toolEyebrow: 'Free tool',
    toolCta: 'Use the tool',
    productEyebrow: 'If you want to go further',
    seeProduct: 'See free demo',
    seeService: 'See how it works',
    buy: 'Buy',
    launch: 'Launch price',
    full: 'Spots are full this week. Join and I will let you know when one opens.',
    consentRequired: 'Tick the box to continue to checkout.',
    waitlistTitle: 'Coming soon',
    waitlistBody: 'I am preparing this programme. Join and you will be the first to know when it is ready.',
    waitlistServiceBody: 'You will be able to book it here very soon. Join and I will let you know when spots open.',
    waitlistGeneralTitle: 'Programmes are on the way',
    waitlistGeneralBody: 'Guides and programmes to train on your own with a clear method. Join and I will let you know when the first one is out.',
    waitlistSubmit: 'Notify me',
    waitlistSuccess: 'You are in. I will email you as soon as it is available.',
    coachingEyebrow: '1:1 coaching',
    coachingTitle: 'Rather do it together?',
    coachingBody: 'A plan built for you, weekly check-ins and direct contact with me. We start with a video call to see if we are a fit.',
    coachingCta: 'See coaching',
    applyCta: 'Apply now',
    authorLabel: 'Written by',
    authorMore: 'About me',
    adLabel: 'Recommended',
  },
} as const satisfies Record<Locale, Record<string, string>>;
