import type { Locale } from '@/i18n/config';

/** Textos de las páginas de sección. Sin precios, testimonios ni datos no confirmados. */
export const PAGES = {
  es: {
    tools: {
      metaTitle: 'Herramientas gratis de entrenamiento y nutrición',
      metaDescription: 'Calculadoras gratis de calorías y macros, proteína y grasa corporal. Resultados al momento, sin registro.',
      h1: 'Herramientas gratis',
      intro: 'Calcula tus números en segundos. Sin registro y con la explicación de cómo se calcula cada resultado.',
    },
    coaching: {
      metaTitle: 'Coaching 1:1 online de entrenamiento y nutrición',
      metaDescription: 'Entrenamiento y nutrición personalizados con seguimiento semanal. Empezamos con una videollamada para ver si encajamos.',
      h1: 'Coaching 1:1 online',
      intro: 'Un plan de entrenamiento y nutrición hecho para ti, con seguimiento cada semana y contacto directo conmigo.',
      howTitle: 'Cómo empezamos',
      how: [
        { h: 'Solicitas tu plaza', p: 'Un formulario de 2 minutos sobre tu objetivo, tu experiencia y tu disponibilidad.' },
        { h: 'Hablamos por videollamada', p: 'Si encajamos, reservas una llamada. Vemos tu caso y te explico cómo trabajaríamos y cuánto cuesta.' },
        { h: 'Empezamos tu plan', p: 'Recibes tu planificación y la ajustamos cada semana según tus datos.' },
      ],
      faqTitle: 'Preguntas frecuentes',
      faq: [
        { q: '¿Cuánto cuesta?', a: 'Depende de la duración que elijas. Te lo explico en la videollamada, sin compromiso.' },
        { q: '¿Tengo que ir a un gimnasio?', a: 'No necesariamente. El plan se adapta al material y al tiempo que tengas.' },
        { q: '¿Es todo online?', a: 'Sí. Trabajamos a distancia con revisiones semanales y contacto directo.' },
      ],
      techniqueTitle: '¿Quieres probar antes?',
      techniqueBody: 'Empieza con una revisión de técnica de 3 vídeos: verás cómo trabajo antes de dar el paso.',
      techniqueCta: 'Ver la revisión de técnica',
    },
    about: {
      metaTitle: 'Sobre mí',
      metaDescription: 'Quién soy, mi titulación y mi método de entrenamiento.',
      h1: 'Sobre mí',
      methodTitle: 'Mi método',
      qualification: 'Titulación',
      city: 'Ciudad',
      social: 'Redes',
    },
    programs: {
      metaTitle: 'Programas y guías de entrenamiento',
      metaDescription: 'Guías y programas para entrenar por tu cuenta con un método claro. Prueba la demo gratis antes de comprar.',
      h1: 'Programas',
      intro: 'Guías y programas para entrenar por tu cuenta. Cada uno tiene una demo gratis para que veas si te encaja.',
      all: 'Todos',
      includes: 'Qué incluye',
      forWho: 'Para quién es',
      demo: 'Demo gratis',
      empty: 'No hay programas con este filtro todavía.',
      kind: 'Infoproducto',
      service: 'Servicio',
      trailer: 'Tráiler',
      insideTitle: 'Lo que hay dentro',
      demoTitle: 'Lee el principio gratis',
      demoMore: 'Aquí se corta la muestra. El capítulo completo y el resto de la guía están en la versión de pago.',
      readDemo: 'Leer la demo',
      getIt: 'Conseguir la guía',
      buyTitle: 'Llévate el sistema completo',
      stuckTitle: '¿Lo aplicas y aun así te estancas?',
      stuckBody: 'La guía te da el sistema. Si te atascas, lo miramos juntos en una videollamada y vemos si tiene sentido trabajar uno a uno.',
      draft: 'Borrador: solo visible en desarrollo',
    },
    learn: {
      metaTitle: 'Aprende: artículos de entrenamiento y nutrición',
      metaDescription: 'Artículos claros y basados en evidencia para perder grasa, ganar músculo, entrenar mejor y comer bien.',
      h1: 'Aprende',
      intro: 'Artículos claros y basados en la evidencia, con el protocolo concreto que aplico con mis clientes.',
      search: 'Buscar artículos',
      searchPlaceholder: 'Ej.: proteína, estancamiento, sentadilla...',
      category: 'Categoría',
      profile: 'Perfil',
      level: 'Nivel',
      all: 'Todos',
      byCategory: 'Por objetivo',
      byProfile: 'Por perfil',
      noResults: 'No hay artículos con estos filtros.',
      empty: 'Los primeros artículos están en camino. Apúntate y te aviso cuando salgan.',
      startHere: 'Empieza aquí',
      more: 'Más artículos',
      home: 'Inicio',
      quickAnswer: 'Respuesta rápida',
      minutes: 'min de lectura',
      published: 'Publicado',
      reviewed: 'Revisado el',
      faq: 'Preguntas frecuentes',
      sources: 'Fuentes',
      related: 'También te puede interesar',
    },
    thanks: {
      metaTitle: 'Gracias por tu compra',
      h1: 'Gracias por tu compra',
      body: 'Te llegará un email de la tienda con tu pedido y el acceso a tu contenido. Revisa también la carpeta de spam.',
      techniqueTitle: '¿Has comprado la revisión de técnica?',
      techniqueCta: 'Enviar mis vídeos',
      coachingTitle: '¿Quieres ir un paso más allá?',
      coachingBody: 'Si buscas un plan hecho para ti y seguimiento semanal, hablamos en una videollamada.',
    },
    send: {
      metaTitle: 'Enviar vídeos para la revisión de técnica',
      h1: 'Envía tus vídeos',
      intro: 'Pega los enlaces a tus 3 vídeos (Google Drive, YouTube "no listado" o iCloud). Comprueba que se puedan ver sin pedir permiso.',
      name: 'Nombre',
      email: 'Email (el mismo de la compra)',
      order: 'Número de pedido',
      video: 'Enlace al vídeo',
      notes: '¿Algo que deba saber? (opcional)',
      notesHint: 'Ejercicio, peso que usas, molestias...',
      privacy: 'He leído la',
      privacyLink: 'política de privacidad',
      submit: 'Enviar vídeos',
      missing: 'Rellena nombre, email, número de pedido y al menos un enlace que empiece por https://.',
      failed: 'No se pudo enviar. Inténtalo de nuevo en un momento.',
      ok: 'Recibido. Te enviaré las correcciones por email.',
    },
    technique: {
      examplesTitle: 'Así corrijo la técnica',
      examplesIntro: 'Correcciones reales a clientes, publicadas con su permiso.',
      play: 'Reproducir vídeo',
      howTitle: 'Cómo funciona',
      how: [
        'Compras la revisión.',
        'Grabas 3 vídeos de tus ejercicios, los subes a Google Drive, a YouTube como "no listado" o a iCloud y me pasas los enlaces en un formulario.',
        'Te devuelvo las correcciones de técnica de cada vídeo.',
      ],
      sendTitle: '¿Ya la has comprado?',
      sendCta: 'Enviar mis vídeos',
    },
  },
  en: {
    tools: {
      metaTitle: 'Free training and nutrition tools',
      metaDescription: 'Free calorie and macro, protein and body fat calculators. Instant results, no sign-up.',
      h1: 'Free tools',
      intro: 'Work out your numbers in seconds. No sign-up, and every result explains how it is calculated.',
    },
    coaching: {
      metaTitle: 'Online 1:1 training and nutrition coaching',
      metaDescription: 'Personalised training and nutrition with weekly check-ins. We start with a video call to see if we are a fit.',
      h1: 'Online 1:1 coaching',
      intro: 'A training and nutrition plan built for you, with weekly check-ins and direct contact with me.',
      howTitle: 'How we start',
      how: [
        { h: 'Apply for a spot', p: 'A 2-minute form about your goal, experience and availability.' },
        { h: 'We talk on a video call', p: 'If we are a fit, you book a call. We go over your case and I explain how we would work and the price.' },
        { h: 'Your plan begins', p: 'You get your plan and we adjust it every week based on your data.' },
      ],
      faqTitle: 'FAQ',
      faq: [
        { q: 'How much does it cost?', a: 'It depends on the length you choose. I explain it on the call, no strings attached.' },
        { q: 'Do I need a gym?', a: 'Not necessarily. The plan adapts to your equipment and time.' },
        { q: 'Is it all online?', a: 'Yes. We work remotely with weekly check-ins and direct contact.' },
      ],
      techniqueTitle: 'Want to try first?',
      techniqueBody: 'Start with a 3-video technique review and see how I work before committing.',
      techniqueCta: 'See the technique review',
    },
    about: {
      metaTitle: 'About me',
      metaDescription: 'Who I am, my qualification and my training method.',
      h1: 'About me',
      methodTitle: 'My method',
      qualification: 'Qualification',
      city: 'City',
      social: 'Social',
    },
    programs: {
      metaTitle: 'Training programmes and guides',
      metaDescription: 'Guides and programmes to train on your own with a clear method. Try the free demo before buying.',
      h1: 'Programmes',
      intro: 'Guides and programmes to train on your own. Each one has a free demo so you can see if it fits.',
      all: 'All',
      includes: 'What is included',
      forWho: 'Who it is for',
      demo: 'Free demo',
      empty: 'No programmes match this filter yet.',
      kind: 'Digital guide',
      service: 'Service',
      trailer: 'Trailer',
      insideTitle: 'What is inside',
      demoTitle: 'Read the beginning for free',
      demoMore: 'The sample stops here. The full chapter and the rest of the guide are in the paid version.',
      readDemo: 'Read the demo',
      getIt: 'Get the guide',
      buyTitle: 'Get the full system',
      stuckTitle: 'Applying it and still stuck?',
      stuckBody: 'The guide gives you the system. If you get stuck, we look at it together on a video call and see whether one-to-one makes sense.',
      draft: 'Draft: only visible in development',
    },
    learn: {
      metaTitle: 'Learn: training and nutrition articles',
      metaDescription: 'Clear, evidence-based articles to lose fat, build muscle, train better and eat well.',
      h1: 'Learn',
      intro: 'Clear, evidence-based articles with the exact protocol I use with my clients.',
      search: 'Search articles',
      searchPlaceholder: 'E.g. protein, plateau, squat...',
      category: 'Category',
      profile: 'Profile',
      level: 'Level',
      all: 'All',
      byCategory: 'By goal',
      byProfile: 'By profile',
      noResults: 'No articles match these filters.',
      empty: 'The first articles are on the way. Join and I will let you know when they are out.',
      startHere: 'Start here',
      more: 'More articles',
      home: 'Home',
      quickAnswer: 'Quick answer',
      minutes: 'min read',
      published: 'Published',
      reviewed: 'Reviewed on',
      faq: 'FAQ',
      sources: 'Sources',
      related: 'You may also like',
    },
    thanks: {
      metaTitle: 'Thanks for your purchase',
      h1: 'Thanks for your purchase',
      body: 'You will receive an email from the store with your order and access to your content. Check your spam folder too.',
      techniqueTitle: 'Bought the technique review?',
      techniqueCta: 'Send my videos',
      coachingTitle: 'Want to go one step further?',
      coachingBody: 'If you want a plan built for you and weekly check-ins, let us talk on a video call.',
    },
    send: {
      metaTitle: 'Send videos for your technique review',
      h1: 'Send your videos',
      intro: 'Paste the links to your 3 videos (Google Drive, unlisted YouTube or iCloud). Make sure they can be viewed without requesting access.',
      name: 'Name',
      email: 'Email (same as your purchase)',
      order: 'Order number',
      video: 'Video link',
      notes: 'Anything I should know? (optional)',
      notesHint: 'Exercise, weight used, any pain...',
      privacy: 'I have read the',
      privacyLink: 'privacy policy',
      submit: 'Send videos',
      missing: 'Fill in name, email, order number and at least one link starting with https://.',
      failed: 'Could not send it. Please try again in a moment.',
      ok: 'Received. I will email you the corrections.',
    },
    technique: {
      examplesTitle: 'How I correct technique',
      examplesIntro: 'Real client corrections, published with their permission.',
      play: 'Play video',
      howTitle: 'How it works',
      how: [
        'You buy the review.',
        'You record 3 videos of your lifts, upload them to Google Drive, YouTube (unlisted) or iCloud, and send me the links through a form.',
        'I send you technique corrections for each video.',
      ],
      sendTitle: 'Already bought it?',
      sendCta: 'Send my videos',
    },
  },
} as const;

export type PagesCopy = (typeof PAGES)['es'];
export const pagesCopy = (locale: Locale) => PAGES[locale] as unknown as PagesCopy;
